# Generated by Django 4.1.3 on 2022-11-30 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('vendor_code', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.FloatField(max_length=15, verbose_name='Цена')),
                ('description', models.TextField(max_length=20000, verbose_name='Описание товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_shops.goodscategorymodel')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_star', models.IntegerField(null=True, verbose_name='Количество оценок 1')),
                ('two_stars', models.IntegerField(null=True, verbose_name='Количество оценок 2')),
                ('three_stars', models.IntegerField(null=True, verbose_name='Количество оценок 3')),
                ('four_stars', models.IntegerField(null=True, verbose_name='Количество оценок 4')),
                ('five_stars', models.IntegerField(null=True, verbose_name='Количество оценок 5')),
                ('average', models.FloatField(max_length=3, verbose_name='Средний рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название магазина')),
                ('short_description', models.CharField(help_text='Краткое описание, которое будет видно на главной странице сайта', max_length=500, verbose_name='Короткое описание')),
                ('full_description', models.TextField(help_text='Полное описание, которое будет видно на странице магазина', max_length=2000, verbose_name='Полное описание')),
                ('rating', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='app_shops.ratingmodel', verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='PersonalOfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(verbose_name='Размер скидки')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_offer', to='app_shops.goodsmodel', verbose_name='Персональные акции и предложения')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_offer', to='app_shops.shopmodel', verbose_name='Персональные акции и предложения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_offer', to=settings.AUTH_USER_MODEL, verbose_name='Персональные акции и предложения')),
            ],
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_shops.ratingmodel', verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_shops.shopmodel'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=20000, verbose_name='Текст отзыва')),
                ('author_name', models.CharField(max_length=50, null=True, verbose_name='Имя автора')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shops.goodsmodel', verbose_name='Товар')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shops.shopmodel', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
