# Generated by Django 4.1.3 on 2022-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Наличие в магазине'),
        ),
    ]
