# Generated by Django 4.1.3 on 2022-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_goodsmodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Количество в магазине'),
        ),
    ]
