# Generated by Django 4.1.3 on 2022-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_balancemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money_spent',
            field=models.IntegerField(default=0, verbose_name='Денег потрачено'),
        ),
        migrations.AddField(
            model_name='userstatusmodel',
            name='status_requirement',
            field=models.IntegerField(default=0, verbose_name='Необходимое количество потраченных покупателем денег'),
        ),
    ]
