# Generated by Django 4.1.3 on 2022-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_ordermodel_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
    ]
